### PR TITLE
Fixes #81 Add UNB & University of Toronto To Associate Members

### LINKED ISSUE #81: Add UNB & University of Toronto Logos To Associate Members
UNB & University of Toronto are both missing from the associate member's section of the homepage. They are both active members and should be added.

### PR DESCRIPTION
**Pull request by bensternthal**

### CODE REVIEW

**Comment by bensternthal** [comment]
@mgielda Howdy, so it looks like the preview github action on this PR failed. I was hoping you could take a look and advise?

**Comment by bensternthal** [comment]
@pgielda given the content of my PR I am surprised we are having this issue. I think this is probably an issue with the github action. I am going to do a PR with a very trivial change and see if I get the same error.

**Comment by bensternthal** [comment]
ok @pgielda I created a PR with a single character change and the github action failed again

https://github.com/chipsalliance/chips-alliance-website/pull/83

Could this possibly be something to do with my account/permissions, or could something else have changed that would cause the Github Action to fail?

**Comment by tgorochowik** [comment]
The issue needs to be investigated, but my guess would be that the issue is that the PR has been created from a forked repository, so far we've been only creating PR from branches within this repo. We need to check whether the privilages can be propagated to external forks

**Comment by bensternthal** [comment]
@tgorochowik I suspected that might be the case. I can redo this pull request against this repo, that might be a quick path to resolution. Can you add me to a group/adjust my permissions so I can create branches in this repo?

**Comment by bensternthal** [comment]
Closing in favor of https://github.com/chipsalliance/chips-alliance-website/pull/84 a PR created against the repo rather than a fork.

**Pull request closed without merging**
