### PR TITLE
Add UNB & University of Toronto To Associate Members

### PR DESCRIPTION
**Pull request by bensternthal**
Add UNB & University of Toronto To Associate Members, includes addition of logos.

### CODE REVIEW

**Comment by bensternthal** [comment]
@mgielda  the github action seems to have run 😄   but it looks like the preview link 404s 😦

**Comment by bensternthal** [comment]
@tgorochowik Thanks for the explanation! No need to do anything, I can be patient ;-)

**Comment by bensternthal** [comment]
@tgorochowik this OK to merge?

**Comment by tgorochowik** [comment]
@bensternthal technically it works and renders correctly :) However I should not be the one to merge this as I am not fully up to date when it comes to members lists etc. Assuming you are now maintaining this, feel free to merge! Otherwise we probably need an ack from Michael or Rob?

**Pull request merged**
