### PR TITLE
Update members.yaml

### PR DESCRIPTION
**Pull request by wendallkaters**
update spelling error

### CODE REVIEW

**Comment by bensternthal** [comment]
@tgorochowik do you know why the comment GH action is failing? Note preview worked [fine on my PR](https://github.com/chipsalliance/chips-alliance-website/pull/151), so is this an issue with Kendall's account permissions?


Screenshot 2024-11-11 at 10 50 35 AM

**Comment by tgorochowik** [comment]
Something must have changed with the privileges settings again. It is most likely caused by the fact that you pushed your branch to the chipsalliance org, while @wendallkaters pushed to their own fork.

We need to take a look at that if we want external contributions to also be able to publish the previews.

**Comment by bensternthal** [comment]
@tgorochowik ok that is what I thought @wendallkaters is a PM coming on to the project so I can give her the same repo permissions that I have. No need to look at adding external contributions.

**Comment by bensternthal** [comment]
OK i invited kendall to this repo, future PRs will be made against this repo rather than a personal branch.

**Pull request closed without merging**
