### PR TITLE
Create Spring Workshop 2021

### PR DESCRIPTION
**Pull request by robmains**
These are the talks, slides, and video of the CHIPS 2021 workshop to be anchored in the events page

### CODE REVIEW

**Comment by cjyabraham** [comment]
I think there should not be spaces between [] and () parts of a link. Did you check this on a local instance?

@mgielda can you set up netlify or something so that we can see previews of PRs?

**Comment by robmains** [comment]
I will review and correct.  I apologize for issues / errors as this is my first time working with this material and environment. 

Happy to turn over to other experts.

Thanks,

Rob

Rob Mains
General Manager
CHIPS Alliance


***@***.***
(c) +1.408.607.4879

**Comment by cjyabraham** [comment]
It's no problem. It takes a bit of getting used to. It's helpful to test on a local dev environment first, if you're open to setting one up, and then it's good to have PRs create their own dev instances so that people can double-check things are correct before merging.

**Comment by robmains** [comment]
Thanks, Chris.

I’d be happy to setup a local dev environment so I can better test things out before submitting a pull request. 
I was a EDA software development years back before going to the dark side, read management. 

Unfortunately, I’ll need some coaching on how to setup a dev environment, but I’m sure others will want this too overtime to be able to update the website accordingly. 

Rob

Rob Mains
General Manager
CHIPS Alliance


***@***.***
(c) +1.408.607.4879

**Pull request merged**
